--liquibase formatted sql

--changeset esab:001-01-create-iam-accounts
CREATE TABLE iam_accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    email       VARCHAR(255),
    phone_number VARCHAR(50),
    password_hash VARCHAR(255),
    status      VARCHAR(50)  NOT NULL,
    email_verified BOOLEAN   NOT NULL DEFAULT FALSE,
    phone_verified BOOLEAN   NOT NULL DEFAULT FALSE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    last_login_ip VARCHAR(45),
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_iam_accounts_uuid UNIQUE (uuid),
    CONSTRAINT uq_iam_accounts_email UNIQUE (email)
);

CREATE INDEX idx_iam_accounts_status ON iam_accounts (status);
--rollback DROP TABLE iam_accounts;

--changeset esab:001-02-create-iam-account-credentials
CREATE TABLE iam_account_credentials (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36)  NOT NULL,
    account_id          BIGINT       NOT NULL,
    provider            VARCHAR(50)  NOT NULL,
    provider_account_id VARCHAR(255) NOT NULL,
    access_token        TEXT,
    refresh_token       TEXT,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_iam_account_credentials_uuid UNIQUE (uuid),
    CONSTRAINT fk_iam_account_credentials_account FOREIGN KEY (account_id) REFERENCES iam_accounts (id),
    CONSTRAINT uq_iam_account_credentials_provider UNIQUE (account_id, provider)
);

CREATE INDEX idx_iam_account_credentials_account_id ON iam_account_credentials (account_id);
--rollback DROP TABLE iam_account_credentials;

--changeset esab:001-03-create-iam-account-devices
CREATE TABLE iam_account_devices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36)  NOT NULL,
    account_id     BIGINT       NOT NULL,
    device_type    VARCHAR(50)  NOT NULL,
    device_name    VARCHAR(255),
    fingerprint    VARCHAR(255),
    user_agent     TEXT,
    push_token     VARCHAR(255),
    last_active_at TIMESTAMPTZ,
    is_trusted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_iam_account_devices_uuid UNIQUE (uuid),
    CONSTRAINT fk_iam_account_devices_account FOREIGN KEY (account_id) REFERENCES iam_accounts (id)
);

CREATE INDEX idx_iam_account_devices_account_id ON iam_account_devices (account_id);
CREATE INDEX idx_iam_account_devices_fingerprint ON iam_account_devices (fingerprint);
--rollback DROP TABLE iam_account_devices;

--changeset esab:001-04-create-iam-account-sessions
CREATE TABLE iam_account_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    account_id  BIGINT       NOT NULL,
    device_id   BIGINT,
    token_hash  VARCHAR(255) NOT NULL,
    ip_address  VARCHAR(45),
    expires_at  TIMESTAMPTZ  NOT NULL,
    is_revoked  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_iam_account_sessions_uuid UNIQUE (uuid),
    CONSTRAINT fk_iam_account_sessions_account FOREIGN KEY (account_id) REFERENCES iam_accounts (id),
    CONSTRAINT fk_iam_account_sessions_device FOREIGN KEY (device_id) REFERENCES iam_account_devices (id)
);

CREATE INDEX idx_iam_account_sessions_account_id ON iam_account_sessions (account_id);
CREATE INDEX idx_iam_account_sessions_token_hash ON iam_account_sessions (token_hash);
--rollback DROP TABLE iam_account_sessions;

--changeset esab:001-05-create-iam-account-otps
CREATE TABLE iam_account_otps (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    account_id BIGINT       NOT NULL,
    code       VARCHAR(20)  NOT NULL,
    purpose    VARCHAR(50)  NOT NULL,
    channel    VARCHAR(50)  NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    is_used    BOOLEAN      NOT NULL DEFAULT FALSE,
    attempts   INTEGER      NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_iam_account_otps_uuid UNIQUE (uuid),
    CONSTRAINT fk_iam_account_otps_account FOREIGN KEY (account_id) REFERENCES iam_accounts (id)
);

CREATE INDEX idx_iam_account_otps_account_id ON iam_account_otps (account_id);
CREATE INDEX idx_iam_account_otps_purpose_channel ON iam_account_otps (account_id, purpose, channel);
--rollback DROP TABLE iam_account_otps;

--changeset esab:001-06-create-iam-account-login-histories
CREATE TABLE iam_account_login_histories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36) NOT NULL,
    account_id     BIGINT      NOT NULL,
    device_id      BIGINT,
    ip_address     VARCHAR(45),
    user_agent     TEXT,
    result         VARCHAR(50) NOT NULL,
    failure_reason TEXT,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_iam_account_login_histories_uuid UNIQUE (uuid),
    CONSTRAINT fk_iam_account_login_histories_account FOREIGN KEY (account_id) REFERENCES iam_accounts (id),
    CONSTRAINT fk_iam_account_login_histories_device FOREIGN KEY (device_id) REFERENCES iam_account_devices (id)
);

CREATE INDEX idx_iam_account_login_histories_account_id ON iam_account_login_histories (account_id);
CREATE INDEX idx_iam_account_login_histories_created_at ON iam_account_login_histories (created_at);
--rollback DROP TABLE iam_account_login_histories;
