--liquibase formatted sql

--changeset esab:002-01-create-ht-hashtags
CREATE TABLE ht_hashtags (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36)  NOT NULL,
    tag            VARCHAR(255) NOT NULL,
    normalized_tag VARCHAR(255) NOT NULL,
    usage_count    BIGINT       NOT NULL DEFAULT 0,
    thread_count   BIGINT       NOT NULL DEFAULT 0,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ht_hashtags_uuid UNIQUE (uuid),
    CONSTRAINT uq_ht_hashtags_tag UNIQUE (tag),
    CONSTRAINT uq_ht_hashtags_normalized_tag UNIQUE (normalized_tag)
);
--rollback DROP TABLE ht_hashtags;

--changeset esab:002-02-create-ht-hashtag-stats
CREATE TABLE ht_hashtag_stats (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(36) NOT NULL,
    hashtag_id   BIGINT      NOT NULL,
    thread_count BIGINT      NOT NULL DEFAULT 0,
    usage_count  BIGINT      NOT NULL DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    created_by   BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by   BIGINT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ht_hashtag_stats_uuid UNIQUE (uuid),
    CONSTRAINT fk_ht_hashtag_stats_hashtag FOREIGN KEY (hashtag_id) REFERENCES ht_hashtags (id),
    CONSTRAINT uq_ht_hashtag_stats_hashtag_id UNIQUE (hashtag_id)
);
--rollback DROP TABLE ht_hashtag_stats;

--changeset esab:002-03-create-ht-hashtag-metadata
CREATE TABLE ht_hashtag_metadata (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    hashtag_id  BIGINT       NOT NULL,
    category    VARCHAR(100),
    language    VARCHAR(10),
    description TEXT,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ht_hashtag_metadata_uuid UNIQUE (uuid),
    CONSTRAINT fk_ht_hashtag_metadata_hashtag FOREIGN KEY (hashtag_id) REFERENCES ht_hashtags (id),
    CONSTRAINT uq_ht_hashtag_metadata_hashtag_id UNIQUE (hashtag_id)
);
--rollback DROP TABLE ht_hashtag_metadata;

--changeset esab:002-04-create-ht-hashtag-moderations
CREATE TABLE ht_hashtag_moderations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    hashtag_id BIGINT      NOT NULL,
    status     VARCHAR(50) NOT NULL,
    reason     TEXT,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ht_hashtag_moderations_uuid UNIQUE (uuid),
    CONSTRAINT fk_ht_hashtag_moderations_hashtag FOREIGN KEY (hashtag_id) REFERENCES ht_hashtags (id),
    CONSTRAINT uq_ht_hashtag_moderations_hashtag_id UNIQUE (hashtag_id)
);
--rollback DROP TABLE ht_hashtag_moderations;

--changeset esab:002-05-create-ht-hashtag-relations
CREATE TABLE ht_hashtag_relations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36) NOT NULL,
    hashtag_a_id        BIGINT      NOT NULL,
    hashtag_b_id        BIGINT      NOT NULL,
    co_occurrence_count BIGINT      NOT NULL DEFAULT 0,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ht_hashtag_relations_uuid UNIQUE (uuid),
    CONSTRAINT fk_ht_hashtag_relations_hashtag_a FOREIGN KEY (hashtag_a_id) REFERENCES ht_hashtags (id),
    CONSTRAINT fk_ht_hashtag_relations_hashtag_b FOREIGN KEY (hashtag_b_id) REFERENCES ht_hashtags (id),
    CONSTRAINT uq_ht_hashtag_relations_pair UNIQUE (hashtag_a_id, hashtag_b_id)
);

CREATE INDEX idx_ht_hashtag_relations_hashtag_a_id ON ht_hashtag_relations (hashtag_a_id);
CREATE INDEX idx_ht_hashtag_relations_hashtag_b_id ON ht_hashtag_relations (hashtag_b_id);
--rollback DROP TABLE ht_hashtag_relations;

--changeset esab:002-06-create-ht-hashtag-usage-hourly
CREATE TABLE ht_hashtag_usage_hourly (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36) NOT NULL,
    hashtag_id  BIGINT      NOT NULL,
    hour_bucket TIMESTAMPTZ NOT NULL,
    count       BIGINT      NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ht_hashtag_usage_hourly_uuid UNIQUE (uuid),
    CONSTRAINT fk_ht_hashtag_usage_hourly_hashtag FOREIGN KEY (hashtag_id) REFERENCES ht_hashtags (id),
    CONSTRAINT uq_ht_hashtag_usage_hourly_bucket UNIQUE (hashtag_id, hour_bucket)
);

CREATE INDEX idx_ht_hashtag_usage_hourly_hashtag_id ON ht_hashtag_usage_hourly (hashtag_id);
CREATE INDEX idx_ht_hashtag_usage_hourly_hour_bucket ON ht_hashtag_usage_hourly (hour_bucket);
--rollback DROP TABLE ht_hashtag_usage_hourly;
