--liquibase formatted sql

--changeset esab:003-01-create-prf-profiles
CREATE TABLE prf_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(36)  NOT NULL,
    account_id   BIGINT       NOT NULL,
    username     VARCHAR(50)  NOT NULL,
    display_name VARCHAR(100),
    bio          TEXT,
    website      VARCHAR(500),
    location     VARCHAR(255),
    avatar_url   VARCHAR(500),
    banner_url   VARCHAR(500),
    visibility   VARCHAR(50)  NOT NULL DEFAULT 'PUBLIC',
    is_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by   BIGINT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by   BIGINT,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profiles_uuid UNIQUE (uuid),
    CONSTRAINT uq_prf_profiles_account_id UNIQUE (account_id),
    CONSTRAINT uq_prf_profiles_username UNIQUE (username),
    CONSTRAINT fk_prf_profiles_account FOREIGN KEY (account_id) REFERENCES iam_accounts (id)
);

CREATE INDEX idx_prf_profiles_visibility ON prf_profiles (visibility);
--rollback DROP TABLE prf_profiles;

--changeset esab:003-02-create-prf-profile-stats
CREATE TABLE prf_profile_stats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    profile_id      BIGINT      NOT NULL,
    follower_count  BIGINT      NOT NULL DEFAULT 0,
    following_count BIGINT      NOT NULL DEFAULT 0,
    thread_count    BIGINT      NOT NULL DEFAULT 0,
    like_count      BIGINT      NOT NULL DEFAULT 0,
    media_count     BIGINT      NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_stats_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_stats_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_prf_profile_stats_profile_id UNIQUE (profile_id)
);
--rollback DROP TABLE prf_profile_stats;

--changeset esab:003-03-create-prf-profile-settings
CREATE TABLE prf_profile_settings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    profile_id           BIGINT      NOT NULL,
    allow_mentions       BOOLEAN     NOT NULL DEFAULT TRUE,
    allow_messages       BOOLEAN     NOT NULL DEFAULT TRUE,
    allow_tagging        BOOLEAN     NOT NULL DEFAULT TRUE,
    show_activity_status BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_settings_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_settings_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_prf_profile_settings_profile_id UNIQUE (profile_id)
);
--rollback DROP TABLE prf_profile_settings;

--changeset esab:003-04-create-prf-profile-activities
CREATE TABLE prf_profile_activities (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36) NOT NULL,
    profile_id     BIGINT      NOT NULL,
    last_active_at TIMESTAMPTZ,
    last_post_at   TIMESTAMPTZ,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_activities_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_activities_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_prf_profile_activities_profile_id UNIQUE (profile_id)
);
--rollback DROP TABLE prf_profile_activities;

--changeset esab:003-05-create-prf-profile-links
CREATE TABLE prf_profile_links (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    profile_id  BIGINT       NOT NULL,
    type        VARCHAR(50)  NOT NULL,
    url         VARCHAR(500) NOT NULL,
    order_index INTEGER      NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_links_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_links_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_prf_profile_links_profile_id ON prf_profile_links (profile_id);
--rollback DROP TABLE prf_profile_links;

--changeset esab:003-06-create-prf-profile-medias
CREATE TABLE prf_profile_medias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    profile_id BIGINT       NOT NULL,
    type       VARCHAR(50)  NOT NULL,
    url        VARCHAR(500) NOT NULL,
    metadata   TEXT,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_medias_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_medias_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_prf_profile_medias_profile_id ON prf_profile_medias (profile_id);
--rollback DROP TABLE prf_profile_medias;

--changeset esab:003-07-create-prf-profile-metadata
CREATE TABLE prf_profile_metadata (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    profile_id BIGINT       NOT NULL,
    key        VARCHAR(255) NOT NULL,
    value      TEXT,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_metadata_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_metadata_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_prf_profile_metadata_profile_id ON prf_profile_metadata (profile_id);
--rollback DROP TABLE prf_profile_metadata;

--changeset esab:003-08-create-prf-profile-usernames
CREATE TABLE prf_profile_usernames (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    profile_id BIGINT      NOT NULL,
    username   VARCHAR(50) NOT NULL,
    is_current BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_usernames_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_usernames_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_prf_profile_usernames_profile_id ON prf_profile_usernames (profile_id);
CREATE INDEX idx_prf_profile_usernames_username ON prf_profile_usernames (username);
--rollback DROP TABLE prf_profile_usernames;

--changeset esab:003-09-create-prf-profile-follows
CREATE TABLE prf_profile_follows (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    follower_profile_id  BIGINT      NOT NULL,
    following_profile_id BIGINT      NOT NULL,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_follows_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_follows_follower FOREIGN KEY (follower_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_prf_profile_follows_following FOREIGN KEY (following_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_prf_profile_follows_pair UNIQUE (follower_profile_id, following_profile_id)
);

CREATE INDEX idx_prf_profile_follows_follower ON prf_profile_follows (follower_profile_id);
CREATE INDEX idx_prf_profile_follows_following ON prf_profile_follows (following_profile_id);
--rollback DROP TABLE prf_profile_follows;

--changeset esab:003-10-create-prf-profile-blocks
CREATE TABLE prf_profile_blocks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(36) NOT NULL,
    blocker_profile_id BIGINT      NOT NULL,
    blocked_profile_id BIGINT      NOT NULL,
    created_by         BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by         BIGINT,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_blocks_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_blocks_blocker FOREIGN KEY (blocker_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_prf_profile_blocks_blocked FOREIGN KEY (blocked_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_prf_profile_blocks_pair UNIQUE (blocker_profile_id, blocked_profile_id)
);

CREATE INDEX idx_prf_profile_blocks_blocker ON prf_profile_blocks (blocker_profile_id);
CREATE INDEX idx_prf_profile_blocks_blocked ON prf_profile_blocks (blocked_profile_id);
--rollback DROP TABLE prf_profile_blocks;

--changeset esab:003-11-create-prf-profile-mutes
CREATE TABLE prf_profile_mutes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36) NOT NULL,
    muter_profile_id BIGINT      NOT NULL,
    muted_profile_id BIGINT      NOT NULL,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by       BIGINT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_mutes_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_mutes_muter FOREIGN KEY (muter_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_prf_profile_mutes_muted FOREIGN KEY (muted_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_prf_profile_mutes_pair UNIQUE (muter_profile_id, muted_profile_id)
);

CREATE INDEX idx_prf_profile_mutes_muter ON prf_profile_mutes (muter_profile_id);
CREATE INDEX idx_prf_profile_mutes_muted ON prf_profile_mutes (muted_profile_id);
--rollback DROP TABLE prf_profile_mutes;

--changeset esab:003-12-create-prf-profile-follow-hashtags
CREATE TABLE prf_profile_follow_hashtags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    profile_id BIGINT      NOT NULL,
    hashtag_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prf_profile_follow_hashtags_uuid UNIQUE (uuid),
    CONSTRAINT fk_prf_profile_follow_hashtags_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_prf_profile_follow_hashtags_hashtag FOREIGN KEY (hashtag_id) REFERENCES ht_hashtags (id),
    CONSTRAINT uq_prf_profile_follow_hashtags_pair UNIQUE (profile_id, hashtag_id)
);

CREATE INDEX idx_prf_profile_follow_hashtags_profile_id ON prf_profile_follow_hashtags (profile_id);
CREATE INDEX idx_prf_profile_follow_hashtags_hashtag_id ON prf_profile_follow_hashtags (hashtag_id);
--rollback DROP TABLE prf_profile_follow_hashtags;
