--liquibase formatted sql

--changeset esab:004-01-create-thr-threads
CREATE TABLE thr_threads (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    author_profile_id    BIGINT      NOT NULL,
    raw_content          TEXT,
    parent_thread_id     BIGINT,
    root_thread_id       BIGINT,
    quote_thread_id      BIGINT,
    like_count           BIGINT      NOT NULL DEFAULT 0,
    reply_count          BIGINT      NOT NULL DEFAULT 0,
    repost_count         BIGINT      NOT NULL DEFAULT 0,
    quote_count          BIGINT      NOT NULL DEFAULT 0,
    bookmark_count       BIGINT      NOT NULL DEFAULT 0,
    view_count           BIGINT      NOT NULL DEFAULT 0,
    status               VARCHAR(50) NOT NULL,
    visibility           VARCHAR(50) NOT NULL,
    reply_restriction    VARCHAR(50),
    is_hide_like_count   BOOLEAN     NOT NULL DEFAULT FALSE,
    is_edited            BOOLEAN     NOT NULL DEFAULT FALSE,
    edited_at            TIMESTAMPTZ,
    scheduled_publish_at TIMESTAMPTZ,
    has_mentions         BOOLEAN     NOT NULL DEFAULT FALSE,
    has_hashtags         BOOLEAN     NOT NULL DEFAULT FALSE,
    has_medias           BOOLEAN     NOT NULL DEFAULT FALSE,
    has_polls            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_threads_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_threads_author FOREIGN KEY (author_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_thr_threads_parent FOREIGN KEY (parent_thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_threads_root FOREIGN KEY (root_thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_threads_quote FOREIGN KEY (quote_thread_id) REFERENCES thr_threads (id)
);

CREATE INDEX idx_thr_threads_author_profile_id ON thr_threads (author_profile_id);
CREATE INDEX idx_thr_threads_parent_thread_id ON thr_threads (parent_thread_id);
CREATE INDEX idx_thr_threads_root_thread_id ON thr_threads (root_thread_id);
CREATE INDEX idx_thr_threads_status ON thr_threads (status);
CREATE INDEX idx_thr_threads_created_at ON thr_threads (created_at);
--rollback DROP TABLE thr_threads;

--changeset esab:004-02-create-thr-thread-medias
CREATE TABLE thr_thread_medias (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          VARCHAR(36)  NOT NULL,
    thread_id     BIGINT       NOT NULL,
    type          VARCHAR(50)  NOT NULL,
    url           VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500),
    width         INTEGER,
    height        INTEGER,
    duration      INTEGER,
    alt_text      TEXT,
    position      INTEGER      NOT NULL DEFAULT 0,
    created_by    BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by    BIGINT,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_medias_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_medias_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id)
);

CREATE INDEX idx_thr_thread_medias_thread_id ON thr_thread_medias (thread_id);
--rollback DROP TABLE thr_thread_medias;

--changeset esab:004-03-create-thr-thread-mentions
CREATE TABLE thr_thread_mentions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    thread_id            BIGINT      NOT NULL,
    mentioned_profile_id BIGINT      NOT NULL,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_mentions_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_mentions_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_thread_mentions_profile FOREIGN KEY (mentioned_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_thr_thread_mentions_pair UNIQUE (thread_id, mentioned_profile_id)
);

CREATE INDEX idx_thr_thread_mentions_thread_id ON thr_thread_mentions (thread_id);
CREATE INDEX idx_thr_thread_mentions_mentioned ON thr_thread_mentions (mentioned_profile_id);
--rollback DROP TABLE thr_thread_mentions;

--changeset esab:004-04-create-thr-thread-hashtags
CREATE TABLE thr_thread_hashtags (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36) NOT NULL,
    thread_id      BIGINT      NOT NULL,
    hashtag_id     BIGINT      NOT NULL,
    position_start INTEGER,
    position_end   INTEGER,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_hashtags_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_hashtags_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_thread_hashtags_hashtag FOREIGN KEY (hashtag_id) REFERENCES ht_hashtags (id)
);

CREATE INDEX idx_thr_thread_hashtags_thread_id ON thr_thread_hashtags (thread_id);
CREATE INDEX idx_thr_thread_hashtags_hashtag_id ON thr_thread_hashtags (hashtag_id);
--rollback DROP TABLE thr_thread_hashtags;

--changeset esab:004-05-create-thr-thread-polls
CREATE TABLE thr_thread_polls (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    thread_id            BIGINT      NOT NULL,
    expires_at           TIMESTAMPTZ NOT NULL,
    allow_multiple_votes BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_polls_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_polls_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT uq_thr_thread_polls_thread_id UNIQUE (thread_id)
);
--rollback DROP TABLE thr_thread_polls;

--changeset esab:004-06-create-thr-thread-poll-options
CREATE TABLE thr_thread_poll_options (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    thread_id  BIGINT       NOT NULL,
    option     VARCHAR(255) NOT NULL,
    position   INTEGER      NOT NULL DEFAULT 0,
    vote_count BIGINT       NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_poll_options_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_poll_options_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id)
);

CREATE INDEX idx_thr_thread_poll_options_thread_id ON thr_thread_poll_options (thread_id);
--rollback DROP TABLE thr_thread_poll_options;

--changeset esab:004-07-create-thr-thread-poll-votes
CREATE TABLE thr_thread_poll_votes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    option_id  BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_poll_votes_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_poll_votes_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_thread_poll_votes_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_thr_thread_poll_votes_option FOREIGN KEY (option_id) REFERENCES thr_thread_poll_options (id),
    CONSTRAINT uq_thr_thread_poll_votes_entry UNIQUE (thread_id, profile_id, option_id)
);

CREATE INDEX idx_thr_thread_poll_votes_thread_id ON thr_thread_poll_votes (thread_id);
CREATE INDEX idx_thr_thread_poll_votes_profile_id ON thr_thread_poll_votes (profile_id);
--rollback DROP TABLE thr_thread_poll_votes;

--changeset esab:004-08-create-thr-thread-link-previews
CREATE TABLE thr_thread_link_previews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    thread_id   BIGINT       NOT NULL,
    url         VARCHAR(500) NOT NULL,
    title       VARCHAR(500),
    description TEXT,
    image_url   VARCHAR(500),
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_link_previews_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_link_previews_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT uq_thr_thread_link_previews_thread_id UNIQUE (thread_id)
);
--rollback DROP TABLE thr_thread_link_previews;

--changeset esab:004-09-create-thr-thread-likes
CREATE TABLE thr_thread_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_likes_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_likes_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_thread_likes_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_thr_thread_likes_pair UNIQUE (thread_id, profile_id)
);

CREATE INDEX idx_thr_thread_likes_thread_id ON thr_thread_likes (thread_id);
CREATE INDEX idx_thr_thread_likes_profile_id ON thr_thread_likes (profile_id);
--rollback DROP TABLE thr_thread_likes;

--changeset esab:004-10-create-thr-thread-reposts
CREATE TABLE thr_thread_reposts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_reposts_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_reposts_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_thread_reposts_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_thr_thread_reposts_pair UNIQUE (thread_id, profile_id)
);

CREATE INDEX idx_thr_thread_reposts_thread_id ON thr_thread_reposts (thread_id);
CREATE INDEX idx_thr_thread_reposts_profile_id ON thr_thread_reposts (profile_id);
--rollback DROP TABLE thr_thread_reposts;

--changeset esab:004-11-create-thr-thread-bookmarks
CREATE TABLE thr_thread_bookmarks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_bookmarks_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_bookmarks_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_thread_bookmarks_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_thr_thread_bookmarks_pair UNIQUE (thread_id, profile_id)
);

CREATE INDEX idx_thr_thread_bookmarks_thread_id ON thr_thread_bookmarks (thread_id);
CREATE INDEX idx_thr_thread_bookmarks_profile_id ON thr_thread_bookmarks (profile_id);
--rollback DROP TABLE thr_thread_bookmarks;

--changeset esab:004-12-create-thr-thread-moderations
CREATE TABLE thr_thread_moderations (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    thread_id            BIGINT      NOT NULL,
    reporter_profile_id  BIGINT      NOT NULL,
    reason               TEXT,
    status               VARCHAR(50) NOT NULL,
    moderator_profile_id BIGINT,
    resolution           TEXT,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_thr_thread_moderations_uuid UNIQUE (uuid),
    CONSTRAINT fk_thr_thread_moderations_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT fk_thr_thread_moderations_reporter FOREIGN KEY (reporter_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_thr_thread_moderations_moderator FOREIGN KEY (moderator_profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_thr_thread_moderations_thread_id ON thr_thread_moderations (thread_id);
CREATE INDEX idx_thr_thread_moderations_status ON thr_thread_moderations (status);
--rollback DROP TABLE thr_thread_moderations;
