--liquibase formatted sql

--changeset esab:006-01-create-ntf-notifications
CREATE TABLE ntf_notifications (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  VARCHAR(36) NOT NULL,
    recipient_profile_id  BIGINT      NOT NULL,
    actor_profile_id      BIGINT,
    type                  VARCHAR(50) NOT NULL,
    entity_type           VARCHAR(50),
    entity_id             BIGINT,
    is_read               BOOLEAN     NOT NULL DEFAULT FALSE,
    group_key             VARCHAR(255),
    actor_count           BIGINT      NOT NULL DEFAULT 0,
    last_actor_profile_id BIGINT,
    created_by            BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by            BIGINT,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ntf_notifications_uuid UNIQUE (uuid),
    CONSTRAINT fk_ntf_notifications_recipient FOREIGN KEY (recipient_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_ntf_notifications_actor FOREIGN KEY (actor_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_ntf_notifications_last_actor FOREIGN KEY (last_actor_profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_ntf_notifications_recipient ON ntf_notifications (recipient_profile_id);
CREATE INDEX idx_ntf_notifications_is_read ON ntf_notifications (recipient_profile_id, is_read);
CREATE INDEX idx_ntf_notifications_created_at ON ntf_notifications (created_at);
CREATE INDEX idx_ntf_notifications_group_key ON ntf_notifications (group_key);
--rollback DROP TABLE ntf_notifications;

--changeset esab:006-02-create-ntf-notification-actors
CREATE TABLE ntf_notification_actors (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36) NOT NULL,
    notification_id  BIGINT      NOT NULL,
    actor_profile_id BIGINT      NOT NULL,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by       BIGINT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ntf_notification_actors_uuid UNIQUE (uuid),
    CONSTRAINT fk_ntf_notification_actors_notification FOREIGN KEY (notification_id) REFERENCES ntf_notifications (id),
    CONSTRAINT fk_ntf_notification_actors_profile FOREIGN KEY (actor_profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_ntf_notification_actors_notification ON ntf_notification_actors (notification_id);
--rollback DROP TABLE ntf_notification_actors;

--changeset esab:006-03-create-ntf-notification-objects
CREATE TABLE ntf_notification_objects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    notification_id BIGINT      NOT NULL,
    entity_type     VARCHAR(50) NOT NULL,
    entity_id       BIGINT      NOT NULL,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ntf_notification_objects_uuid UNIQUE (uuid),
    CONSTRAINT fk_ntf_notification_objects_notification FOREIGN KEY (notification_id) REFERENCES ntf_notifications (id)
);

CREATE INDEX idx_ntf_notification_objects_notification ON ntf_notification_objects (notification_id);
--rollback DROP TABLE ntf_notification_objects;

--changeset esab:006-04-create-ntf-notification-deliveries
CREATE TABLE ntf_notification_deliveries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    notification_id BIGINT      NOT NULL,
    channel         VARCHAR(50) NOT NULL,
    status          VARCHAR(50) NOT NULL,
    sent_at         TIMESTAMPTZ,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ntf_notification_deliveries_uuid UNIQUE (uuid),
    CONSTRAINT fk_ntf_notification_deliveries_notification FOREIGN KEY (notification_id) REFERENCES ntf_notifications (id)
);

CREATE INDEX idx_ntf_notification_deliveries_notification ON ntf_notification_deliveries (notification_id);
CREATE INDEX idx_ntf_notification_deliveries_status ON ntf_notification_deliveries (status);
--rollback DROP TABLE ntf_notification_deliveries;

--changeset esab:006-05-create-ntf-notification-settings
CREATE TABLE ntf_notification_settings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    profile_id      BIGINT      NOT NULL,
    like_enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    reply_enabled   BOOLEAN     NOT NULL DEFAULT TRUE,
    mention_enabled BOOLEAN     NOT NULL DEFAULT TRUE,
    follow_enabled  BOOLEAN     NOT NULL DEFAULT TRUE,
    repost_enabled  BOOLEAN     NOT NULL DEFAULT TRUE,
    quote_enabled   BOOLEAN     NOT NULL DEFAULT TRUE,
    push_enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    email_enabled   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_by      BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ntf_notification_settings_uuid UNIQUE (uuid),
    CONSTRAINT fk_ntf_notification_settings_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_ntf_notification_settings_profile_id UNIQUE (profile_id)
);
--rollback DROP TABLE ntf_notification_settings;

--changeset esab:006-06-create-ntf-notification-counters
CREATE TABLE ntf_notification_counters (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(36) NOT NULL,
    profile_id   BIGINT      NOT NULL,
    unread_count BIGINT      NOT NULL DEFAULT 0,
    created_by   BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by   BIGINT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ntf_notification_counters_uuid UNIQUE (uuid),
    CONSTRAINT fk_ntf_notification_counters_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_ntf_notification_counters_profile_id UNIQUE (profile_id)
);
--rollback DROP TABLE ntf_notification_counters;
