--liquibase formatted sql

--changeset esab:007-01-create-grp-groups
CREATE TABLE grp_groups (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    owner_profile_id BIGINT       NOT NULL,
    name             VARCHAR(100) NOT NULL,
    slug             VARCHAR(100) NOT NULL,
    description      TEXT,
    avatar_url       VARCHAR(500),
    banner_url       VARCHAR(500),
    visibility       VARCHAR(50)  NOT NULL DEFAULT 'PUBLIC',
    status           VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
    requires_approval BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by       BIGINT,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_groups_uuid UNIQUE (uuid),
    CONSTRAINT uq_grp_groups_slug UNIQUE (slug),
    CONSTRAINT fk_grp_groups_owner FOREIGN KEY (owner_profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_grp_groups_owner_profile_id ON grp_groups (owner_profile_id);
CREATE INDEX idx_grp_groups_visibility ON grp_groups (visibility);
CREATE INDEX idx_grp_groups_status ON grp_groups (status);
--rollback DROP TABLE grp_groups;

--changeset esab:007-02-create-grp-group-stats
CREATE TABLE grp_group_stats (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(36) NOT NULL,
    group_id     BIGINT      NOT NULL,
    member_count BIGINT      NOT NULL DEFAULT 0,
    thread_count BIGINT      NOT NULL DEFAULT 0,
    created_by   BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by   BIGINT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_group_stats_uuid UNIQUE (uuid),
    CONSTRAINT fk_grp_group_stats_group FOREIGN KEY (group_id) REFERENCES grp_groups (id),
    CONSTRAINT uq_grp_group_stats_group_id UNIQUE (group_id)
);
--rollback DROP TABLE grp_group_stats;

--changeset esab:007-03-create-grp-group-members
CREATE TABLE grp_group_members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36) NOT NULL,
    group_id    BIGINT      NOT NULL,
    profile_id  BIGINT      NOT NULL,
    role        VARCHAR(50) NOT NULL,
    status      VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    muted_until TIMESTAMPTZ,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_group_members_uuid UNIQUE (uuid),
    CONSTRAINT fk_grp_group_members_group FOREIGN KEY (group_id) REFERENCES grp_groups (id),
    CONSTRAINT fk_grp_group_members_profile FOREIGN KEY (profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_grp_group_members_pair UNIQUE (group_id, profile_id)
);

CREATE INDEX idx_grp_group_members_group_id ON grp_group_members (group_id);
CREATE INDEX idx_grp_group_members_profile_id ON grp_group_members (profile_id);
CREATE INDEX idx_grp_group_members_role ON grp_group_members (role);
CREATE INDEX idx_grp_group_members_status ON grp_group_members (status);
--rollback DROP TABLE grp_group_members;

--changeset esab:007-04-create-grp-group-rules
CREATE TABLE grp_group_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    group_id    BIGINT       NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    position    INTEGER      NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_group_rules_uuid UNIQUE (uuid),
    CONSTRAINT fk_grp_group_rules_group FOREIGN KEY (group_id) REFERENCES grp_groups (id)
);

CREATE INDEX idx_grp_group_rules_group_id ON grp_group_rules (group_id);
--rollback DROP TABLE grp_group_rules;

--changeset esab:007-05-create-grp-group-invitations
CREATE TABLE grp_group_invitations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(36)  NOT NULL,
    group_id           BIGINT       NOT NULL,
    inviter_profile_id BIGINT       NOT NULL,
    invitee_profile_id BIGINT       NOT NULL,
    status             VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    token              VARCHAR(255) NOT NULL,
    expires_at         TIMESTAMPTZ,
    created_by         BIGINT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by         BIGINT,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_group_invitations_uuid UNIQUE (uuid),
    CONSTRAINT uq_grp_group_invitations_token UNIQUE (token),
    CONSTRAINT fk_grp_group_invitations_group FOREIGN KEY (group_id) REFERENCES grp_groups (id),
    CONSTRAINT fk_grp_group_invitations_inviter FOREIGN KEY (inviter_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_grp_group_invitations_invitee FOREIGN KEY (invitee_profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_grp_group_invitations_group_id ON grp_group_invitations (group_id);
CREATE INDEX idx_grp_group_invitations_invitee_profile_id ON grp_group_invitations (invitee_profile_id);
CREATE INDEX idx_grp_group_invitations_status ON grp_group_invitations (status);
--rollback DROP TABLE grp_group_invitations;

--changeset esab:007-06-create-grp-group-member-requests
CREATE TABLE grp_group_member_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  VARCHAR(36) NOT NULL,
    group_id              BIGINT      NOT NULL,
    requester_profile_id  BIGINT      NOT NULL,
    status                VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    reviewed_by_profile_id BIGINT,
    review_note           TEXT,
    created_by            BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by            BIGINT,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_group_member_requests_uuid UNIQUE (uuid),
    CONSTRAINT fk_grp_group_member_requests_group FOREIGN KEY (group_id) REFERENCES grp_groups (id),
    CONSTRAINT fk_grp_group_member_requests_requester FOREIGN KEY (requester_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_grp_group_member_requests_reviewer FOREIGN KEY (reviewed_by_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT uq_grp_group_member_requests_pair UNIQUE (group_id, requester_profile_id)
);

CREATE INDEX idx_grp_group_member_requests_group_id ON grp_group_member_requests (group_id);
CREATE INDEX idx_grp_group_member_requests_requester_profile_id ON grp_group_member_requests (requester_profile_id);
CREATE INDEX idx_grp_group_member_requests_status ON grp_group_member_requests (status);
--rollback DROP TABLE grp_group_member_requests;

--changeset esab:007-07-create-grp-group-threads
CREATE TABLE grp_group_threads (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    group_id   BIGINT      NOT NULL,
    thread_id  BIGINT      NOT NULL,
    is_pinned  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_group_threads_uuid UNIQUE (uuid),
    CONSTRAINT fk_grp_group_threads_group FOREIGN KEY (group_id) REFERENCES grp_groups (id),
    CONSTRAINT fk_grp_group_threads_thread FOREIGN KEY (thread_id) REFERENCES thr_threads (id),
    CONSTRAINT uq_grp_group_threads_pair UNIQUE (group_id, thread_id)
);

CREATE INDEX idx_grp_group_threads_group_id ON grp_group_threads (group_id);
CREATE INDEX idx_grp_group_threads_thread_id ON grp_group_threads (thread_id);
CREATE INDEX idx_grp_group_threads_is_pinned ON grp_group_threads (is_pinned);
--rollback DROP TABLE grp_group_threads;

--changeset esab:007-08-create-grp-group-moderation-actions
CREATE TABLE grp_group_moderation_actions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    group_id             BIGINT      NOT NULL,
    target_profile_id    BIGINT      NOT NULL,
    moderator_profile_id BIGINT      NOT NULL,
    action_type          VARCHAR(50) NOT NULL,
    reason               TEXT,
    expires_at           TIMESTAMPTZ,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grp_group_moderation_actions_uuid UNIQUE (uuid),
    CONSTRAINT fk_grp_group_moderation_actions_group FOREIGN KEY (group_id) REFERENCES grp_groups (id),
    CONSTRAINT fk_grp_group_moderation_actions_target FOREIGN KEY (target_profile_id) REFERENCES prf_profiles (id),
    CONSTRAINT fk_grp_group_moderation_actions_moderator FOREIGN KEY (moderator_profile_id) REFERENCES prf_profiles (id)
);

CREATE INDEX idx_grp_group_moderation_actions_group_id ON grp_group_moderation_actions (group_id);
CREATE INDEX idx_grp_group_moderation_actions_target_profile_id ON grp_group_moderation_actions (target_profile_id);
CREATE INDEX idx_grp_group_moderation_actions_action_type ON grp_group_moderation_actions (action_type);
--rollback DROP TABLE grp_group_moderation_actions;
